### ISSUE TITLE
[Question] Anyway to boost API speeds?

### ISSUE THREAD

**Issue by JKeyzs** [victornpb/deleteDiscordMessages#138]
I have super fast internet and the API speeds are super slow to delete. I only have about 2200 messages to be deleted, and it said 
5134ms delay ......

**Comment by victornpb** [comment]
This limit is imposed by discord API

**Comment by LNATION13** [comment]
But why is it so slow is the Question. like is it supposed to be slow? or is it supposed to be fast? the question im trying to ask ere is, is there a way you as the Owner could tell us why the API is so slow!

**Comment by victornpb** [comment]
It is not like the API is slow, but it is intentionally throttling you from doing too many things.

I'd assume since discord stores chronological data using snowflakes, deleting stuff is computationally heavy since that makes their indexes obsolete, and would require them to shuffle a lot of data, they are just trying to prevent a high load.

What you can do, is make your activity looks less like a robot and more like a human, don’t push the speed too hard and if you get throttled slow things down and wait a bit, so you don’t get throttled even further.

Like in my experience I only get throttled for about a few seconds, but people reported being being cooled down for like minutes

**Comment by LNATION13** [comment]
Yes i totally agree with you i use Grease monkey on Firefox how do i Slow things down that way
