### ISSUE TITLE
[Question] Error 403 when attempting deletion

### ISSUE THREAD

**Issue by Esmeralda2001** [victornpb/deleteDiscordMessages#215]
So recently I have left a server, however I now very much regret not deleting my messages before leaving. 
I do in fact have access to the Guild ID + channel ID's but when I try to delete my messages I get an error 403

I have both checked and unchecked NSFW (as there is 1 channel labelled as such) but this did not change anything. 
My question: is it at all possible to delete messages from a server you left on your own? And if not, what could be the reason as to why I get an error 403 for attempting to do so? 

Thank you in advance.

**Comment by mcmcford** [comment]
you need to be in the server to delete messages from said server

**Comment by Esmeralda2001** [comment]
> you need to be in the server to delete messages from said server
> 
> You have no authorisation over that server, even your own messages since you aren't a member

Yeah that's what I feared to be honest. I also recently realized that you cannot delete from hidden channels either. So even if I hadn't left I would not have been able to complete deletion, as several channels that I had participated in were made hidden a while before I left the server. 

It's a shame how little control we actually have over our own messages. I **should** be able to delete my messages from a server, regardless of whether I'm a member or not, because they're **my** messages and a user's right to privacy is important. It's a shame that Discord's privacy policy sucks so much regarding this. I even contacted them to see if it was possible to have my messages deleted by them, but was told that no such feature exists (obviously) and to vote on the Feedback threads. 
Which does have one thread requesting for a deletion feature, but it's been up for several years with a lot of upvotes and Discord has yet to do anything with it... I doubt they will. Even though it should be possible for them to do so as they've already got an option to retrieve all messages you've ever sent. So long as they have access to the message id's they can delete anything (because I know for a fact they have deleted messages before upon request if the messages contain sensitive information such as a user's location)

Anyway that was just a little rant regarding Discord being such a pain when it comes to user privacy. I'm aware of the fact that the contributors of this extension can't do anything about this. Props to them for attempting to create such a feature though, being able to completely delete messages from servers you're participating in is better than not being able to at all!

Thank you for the answer. 
Cheers and have a good day/night!

**Comment by mcmcford** [comment]
I found that the best way to understand this scripts capabilities to to think of it as yourself, if you couldn't delete them due to the fact your not in the server, the channel has been hidden etc, then the bot can't delete it.

But you are completely right, discord should have a feature to delete your messages selectively, even in servers or channels that you don't have access to.

It starts to make me think about how they would handle requests for erasure of data about a person, if they were to delete the users account, email, password hash, pfp etc etc but leave the messages, would that count as data erasure since the data has been anonymised and can't be linked back to a single user?

_That being said, doesn't the 'deleted user' profile that comes up as the sender of messages from a deleted account keep the discriminator?_  - never mind, just checked and it looks like they have changed that, now it defaults to 0000

Even then, you still have discord servers who use message loggers and bots, that is data collected on you, as an individual, but would discord be responsible for deleting that data upon a request for erasure or is that down to the server owner? It is being hosted by discord but unless discord worked with the bot makers to create a way to link logs to users easily, from their admin point of view at least.

In my opinion, there are a lot of grey areas that I doubt we will get answers to but I guess the same can be said about many services.

I think the best way to think of it is that discord is basically a web browser. People can make selfbots in java script that will simple log every message it sees. So the solution? watch what you say - but I know that things happen, you think you can be open with certain groups and say what you want then there is an unexpected falling out etc etc

Its a rough situation to be in. But anyway, I'm glad I could answer your question =)

**Comment by Esmeralda2001** [comment]
You're absolutely right that that's how one should look at it. I suppose what made me think otherwise was the fact that deleting from closed DM's is possible (so long as you've got the ID), which made me think that maybe there was a different issue when it came to receiving the error when trying to delete from a server I left. In hindsight I should've realized sooner that of course you would be able to delete from a closed DM, as closing one simply means hiding it from yourself. 

I have read about one case where someone requested for data erasure but Discord did not oblige. They were told that they'd only delete messages containing any sensitive information (and I believe you have to provide the message id's yourself) but would otherwise not delete. Whether this still counts as data erasure, I don't think so. I don't remember what was said about this exactly anymore so I'd take this with a grain of salt but I think Discord being unwilling to erase everything from a user is breaking the law in some countries (Canada, EU countries, UK) and I have seen people reporting this to websites that track this kind of thing. I think Discord has yet to be fined for this and whether they would care or not would highly depend on how high the fine is, as plenty of companies would rather pay up than implement proper privacy for it's users. 

Bot loggers are a very interesting point you bring up. Discord's current bot API does provide ways for logging I believe. In which case I'd say that Discord does hold some responsibility here since they gave explicit access to bot owners to log. I do not think that Discord would be responsible for the data per say, as they are not the ones logging them but merely providing the tools to do so. Frankly it sounds impossible to have Discord enforce bot owners to delete data they have already gathered. 

It was indeed the fact that I left a friend group after we grew apart from each other. Thankfully I am a cautious person and rarely share sensitive information so in this case I just wanted to have the knowledge that at least my side of the history is erased. But nothing I can do about that now and that's fine it's life we cannot control everything that we'd like to control sadly. 

I will be closing this now as my question has been answered. Thank you again!
