### ISSUE TITLE
[Enhancement] Handy bookmarklet

### ISSUE THREAD

**Issue by NLDev** [victornpb/deleteDiscordMessages#22]
Just an idea: Making a handy bookmarklet for it? 
Tried to minify the code and paste it like `javascript:(function(){...` as bookmarklet. 
PopUp opens fine. [This line](https://github.com/victornpb/deleteDiscordMessages/blob/master/deleteDiscordMessages.js#L85) however makes the whole page go blank/white with the text "Looking good!". Removing the line seems to work. getting the AuthToken, AuthorID and ChannelID appears to work as well, but deleting does't. I guess the bookmarklet doesn't have access to the same context in which devtools is running, but haven't had time to debug in depth

**Comment by victornpb** [comment]
I think it is doable, I've done a lot of bookmarklets in the past. I'll have to check if I'm not missing any semicolons, and I have to strip all the comments, and URL encode it.

I just haven't done it because it is not something that is easy to explain to the average user, lots of things to get wrong. For example I expect a lot of people wondering why this doesn't work `https://javascript:(func...`

I use this chrome extension to create bookmarklets (It also doesn't like comments.)
https://chrome.google.com/webstore/detail/bookmarklet-ide/peebnjhlifoemfpcffdlbcdppmikglek

**Comment by NLDev** [comment]
The usability is certainly an argument... Making a GitHub Page with a drag'n'droppable Bookmarklet link seems a bit overkill as well. It doesn't work in Markdown sadly:

<a href="javascript:void((function(){alert("Hello GitHub!")})());">Drag Me!</a>

**Comment by victornpb** [comment]
I could make a github page using rollup and a node script, I’ll make some experiments when I have time.

But I also dislike the idea of encouraging people to run minified code on their browsers, because it could be a security issue.

I was very deliberate in making the code verbose with comments and without any external library.

I know the average user doesn’t know how to inspect code, but at the same time the code is publicly available, so anyone can audit it and know for sure I’m not doing anything sketchy.

**Comment by MeowMeowCatPersonThing** [comment]
Any updates on this?

**Comment by victornpb** [comment]
> Any updates on this?

Yes! sorry for taking so long, but I made it available as a installable user-script.
Take a look at the new readme in the front page, should be much easier to non-techinicall ppl and more convenient to use.

Any feedback is appreciated.

<img width="1419" alt="Screen Shot 2020-07-05 at 1 25 57 AM" src="https://user-images.githubusercontent.com/3372598/86538487-adff0a80-becc-11ea-92bf-b1d04aea6ad7.png">
