### ISSUE TITLE
[Question] Rate limit

### ISSUE THREAD

**Issue by Mtrnt** [victornpb/deleteDiscordMessages#92]
Hey,
is there a way to change rate limit? Initially it deletes about 30 messages, then I wait out the delay and at the end delete delay is set to about 70 seconds per message.

**Comment by victornpb** [comment]
The cooldown, is determined on the discord side, even tho I never experienced cooldown greater than a few seconds, in the past a few people related being cooled down for several minutes, this is mostly due to discord noticing some unusual load on their servers coming from you. I suggest being gentle and respecting it. Try to go easy and not delete too much stuff at one time, as you can have your account terminated if you abuse their system.
